language: python
python:
  - 2.6
  - 2.7
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update
  - sudo apt-get install -qq gfortran
  # numpy is installed anyway, even on py!=2.7 where system site-packages are never available. keep it here for completeness
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq libgeos-3.2.2 libgeos-dev libgeos-c1  # for matplotlib basemap
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  - wget -q -O - 'https://github.com/obspy/wheelhouse/archive/master.tar.gz' | tar -C /tmp -xzf -
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then sudo apt-get install -qq python-dev python-scipy python-lxml python-sqlalchemy python-m2crypto python-mock; else pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master scipy lxml sqlalchemy m2crypto; pip install mock; fi
  - pip install https://github.com/yarikoptic/coveralls-python/archive/master.zip
  - pip install --use-mirrors geographiclib
  - pip install --use-mirrors suds-jurko
  - pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master matplotlib==1.3.1
  #- pip install --use-wheel --no-index --find-links=/tmp/wheelhouse-master basemap
  - pip install https://github.com/megies/basemap/archive/v1.0.7_geos_link_fix.zip
  - pip install --use-mirrors flake8
  # Future 0.11.3 has some issues and essentially does not work under Python 2.x. Older
  # versions have some other issues. The master more or less resolves them.
  # XXX: Replace once a new future version has been released!
  - pip install --use-mirrors https://github.com/PythonCharmers/python-future/archive/master.zip
  - pip freeze
install:
  - git remote add obspy git://github.com/obspy/obspy.git
  - git fetch obspy --tags
  - git fetch origin --tags
  - DEPTH=300; while [ "$(git describe 2> /dev/null)" == "" ]; do DEPTH=$(($DEPTH+200)); git fetch origin --depth=$DEPTH --quiet; done # continue fetching more older commits until git describe is able to reach the last tagged version
  - git status
  - pip install --no-deps --use-mirrors .
  - git status
script:
  # We change directories to make sure that python won't find the copy
  # of obspy in the source directory, see
  # https://github.com/numpy/numpy/blob/master/.travis.yml#L44
  - mkdir empty
  - cd empty
  - MODULELIST=`python -c "from obspy.core.util import DEFAULT_MODULES as MODULES; print('obspy.' + ',obspy.'.join(MODULES))"`
  - coverage run --source=$MODULELIST -m obspy.core.scripts.runtests -n travis-ci -r --keep-images --keep-only-failed-images
after_success:
  - coveralls
notifications:
    email: false
# Upload any potentially produced diffs and produced images to imgur after a test failure.
after_failure:
  - cd
  - wget "http://imgur.com/tools/imgurbash.sh"
  - for FILE in `find . -regex '.*/tests/images/testrun/.*png' | sort`; do echo $FILE; bash imgurbash.sh $FILE; done
