# https://travis-ci.org/obspy/vcr

language: python

matrix:
  include:
    - os: linux
      env: PYTHON_VERSION=2.7
    - os: linux
      env: PYTHON_VERSION=3.4
    - os: linux
      env: PYTHON_VERSION=3.5
    - os: linux
      env: PYTHON_VERSION=3.6
    - os: osx
      env: PYTHON_VERSION=2.7
    - os: osx
      env: PYTHON_VERSION=3.4
    - os: osx
      env: PYTHON_VERSION=3.5
    - os: osx
      env: PYTHON_VERSION=3.6

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py install

script:
  - python setup.py test

notifications:
  email: false
