# https://travis-ci.org/obspy/vcr

language: python

os:
  - linux
  - osx

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "pypi"
  - "pypy3"

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - python setup.py install

script:
  - python setup.py test

notifications:
  email: false
