# https://ci.appveyor.com/project/obspy/vcr/

environment:
  matrix:

    - PYTHON: "C:\\Miniconda" 
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda3"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"


install:
  # Prepend Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Create a conda environment using the required python version
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"
  # additional dependencies
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python setup.py install

build: false

test_script:
  - "python setup.py test"

matrix:
  # enable fast fail strategy
  fast_finish: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
