# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml

package:
  name: obspy
  version: "0.10.1"

source:
  fn: obspy-master.zip
  url: https://pypi.python.org/packages/source/o/obspy/obspy-0.10.1.zip#md5=0d32bcf8e9534d32c91efee84291bad3
  # alternatively we can use a local path, however this fails with
  # shutil.Error: [('/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # '/path/to/miniconda3/conda-bld/work/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # "[Errno 2] No such file or directory: '/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf'")]
  #path: ../../../..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - flake8
  run:
    - python
    - setuptools
    - future
    - numpy
    - mock  # [py2k]
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - flake8

test:
  imports:
    - obspy
    - obspy.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
