package:
  name: obspy
  version: "0.10.0rc1"

source:
  fn: obspy-master.zip
  url: https://github.com/obspy/obspy/archive/master.zip
  # alternatively we can use a local path, however this fails with
  # shutil.Error: [('/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # '/path/to/miniconda3/conda-bld/work/misc/docs/source/tutorial/ObsPyTutorial.pdf',
  # "[Errno 2] No such file or directory: '/path/to/obspy/misc/docs/source/tutorial/ObsPyTutorial.pdf'")]
  #path: ../../../..

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
    - numpy
    - mock  # [py2k]
    - argparse # [py26]
    - future
    - matplotlib
    - lxml
    - sqlalchemy
    - scipy
  run:
    - python
    - future
    - numpy
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - argparse # [py26]
    - flake8

test:
  imports:
    - obspy
    - obspy.mseed

about:
  home: http://obspy.org
  license: LGPLv3
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
