# CircleCI is used exclusively to test code formatting.
# Thus ObsPy does not even have to be installed.
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            /opt/conda/bin/conda install -y flake8 pep8-naming

      - run:
          name: run linting
          command: |
            /opt/conda/bin/flake8 --version
            /opt/conda/bin/flake8 obspy
          name: run file size check
          command: |
            git diff --name-only $CIRCLE_COMPARE_URL | xargs -I {} find {} -size +5 | wc -l
