# CircleCI is used exclusively to test code formatting.
# Thus ObsPy does not even have to be installed.
version: 2
jobs:
  build:
    docker:
      - image: continuumio/anaconda:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            /opt/conda/bin/conda install -y flake8 pep8-naming

      - run:
          name: run linting
          command: |
            /opt/conda/bin/flake8 --version
            /opt/conda/bin/flake8 obspy
            EXIT_CODE=0;for SIZE in $(git log --pretty='format:%H' master.. | git cat-file --batch-check='%(objectsize)'); do if (( $SIZE > 235 )); then echo "File you added exceeds our limit of 500k"; EXIT_CODE=1; fi; (exit $EXIT_CODE) done
